### PR TITLE
CI: Rewrite for OBS 28 and build on Github Actions

### PR DESCRIPTION
**Pull request by norihiro**
Known issues
- [x] ~~libpng for macOS arm64 is not detected.~~ The libpng is only necessary for libvncserver. Libvncclient does not require libpng.
- [x] Build flow of libpng for Windows does not produce library. Log said `Found PNG: D:\a\obs-vnc\obs-vnc\libvncserver/deps/libpng/RelWithDebInfo/libpng16_static.lib (found version "1.6.37")`.

- [ ] The commit is reviewed by yourself.
- [ ] The code is tested.
  - [x] macOS on (`x86_64`) is tested.
- [x] Document is up to date or not necessary to be changed.
- [x] The commit is compatible with repository's license.

### CODE REVIEW

**Comment by norihiro** [comment]
These selections are listed on macOS, x86_64. It looks same as that on Linux.
Screenshot_2022-08-12_23-14-09

**Comment by norihiro** [comment]
The build flow is similar to norihiro/obs-text-pthread and it was not ok for macOS on Apple Silicon. Maybe this script won't work.

**Comment by NorseGaud** [comment]
The arm64 issue here is weird. Any way to rewrite the CI to run from a bash wrapper script instead of being so dependent on github actions? That way I can run it locally if need be? More than happy to donate to finalize this support for arm64 OBS.

**Comment by norihiro** [comment]
> Any way to rewrite the CI to run from a bash wrapper script instead of being so dependent on github actions?

Actually I have rewritten some code so that it's less dependent on GitHub Actions than obs-plugintemplate.

`.github/workflows/main.yml` is the main workflow to build this plugin. In the workflow for macOS, if you build on your local machine,
- `Setup Environment` is unnecessary.
- `Install Apple Developer Certificate` is unnecessary.
- `Set Signing Identity` is unnecessary.
- `Download obs-studio development environment` This is a common step among my all other OBS plugins and doing these things.
  - This step checkouts https://github.com/norihiro/obs-studio-devel-action
  - and runs `scripts/macos-download.sh -a arm64 -o 28 -d /tmp/deps-28-arm64 --no-qt`
- `Install libvncserver`
  - This step just runs `ci/macos/install-libvncserver-arm64.sh`

I tried to hack `brew` to download ARM64 prebuilt binaries including `libvncserver` on x86_64 machine because GitHub Actions only provides x86_64.
However, homebrew does not support such usage, they just provide for a local machine usage.
What I should do ideally is not relying on homebrew but build these libraries by myself in the script so that I can provide both x86_64 and arm64 architecture. There is a way to combine two or more different architecture libraries into one file. The best thing would be making just one universal package so that users won't confuse which file to be download.

**Comment by norihiro** [comment]
@NorseGaud The sponsor is also welcome.
Something I'm thinking of is using a build scheme like https://github.com/obsproject/obs-deps/
They build some libraries for both `x86_64` and `arm64` then merge it.
I recently found a useful tool https://github.com/mxschmitt/action-tmate which would be helpful for me to debug the build flow.
I was originally started to transfer remote macOS screen to OBS running on Linux. However, a few years ago, after replacing the mac, an issue raised that a VNC session viewing macOS screen causes that macOS to be locked and the user on the mac cannot unlock it. That mac is owned by someone else so I didn't have enough time to debug the issue. Later, I started to use obs-ndi instead of obs-vnc. So, the sponsor would be helpful for me to motivate to maintain this plugin.

**Comment by norihiro** [comment]
I'm seeing an error below while configuring gnutls for arm64, which I've not found how to fix.
```
checking for NETTLE... yes
checking for HOGWEED... no
configure: error: 
  ***
  *** Libhogweed (nettle's companion library) 3.4.1 was not found. Note that you must compile nettle with gmp support.
```

**Comment by norihiro** [comment]
Now succeeded to build gnutls using dependency libraries from the bottle.
Next, I will make the universal library using `lipo`, adjust rpath, and build libvncserver.

**Comment by norihiro** [comment]
This PR is superseded by another PR #32.

**Pull request closed without merging**
